{
  inputs,
  pkgs,
  ...
}:
let
  # Configure formatter.
  treefmtEval = inputs.treefmt-nix.lib.evalModule pkgs {
    projectRootFile = ".git/config";
    # schemas/*: generated by `just gen-schema`, which pins its own JSON
    # serialization -- prettier reflowing it makes `gen-schema --check` fail.
    settings.global.excludes = [
      "external/*"
      "schemas/*"
    ];

    # Markdown, JSON, YAML, etc.
    programs.prettier = {
      enable = true;
      package = pkgs.prettier;
    };

    # Python. ruff-check autofixes lint, ruff-format lays the code out; enabling
    # only the first leaves the repo with no Python formatter at all.
    programs.ruff-check.enable = true;
    programs.ruff-format.enable = true;

    # Shell.
    programs.shfmt = {
      enable = true;
      indent_size = 4;
    };

    programs.shellcheck.enable = true;
    settings.formatter.shellcheck = {
      options = [
        "-e"
        "SC1091"
      ];
    };

    # Lua.
    programs.stylua.enable = true;

    # Nix.
    programs.nixfmt.enable = true;

    # Typos.
    programs.typos.enable = false;
  };

  treefmt = treefmtEval.config.build.wrapper;
in
treefmt
