[project]
name = "speciai"
authors = [
  { name = "Martin Fontanet", email = "martin.fontanet@epfl.ch" },
  { name = "Cyril Matthey-Doret", email = "cyril.matthey-doret@epfl.ch" },
  { name = "Robin Franken", email = "robin.franken@epfl.ch" },
]
description = "Extraction of structured data from specimen pictures."
readme = "README.md"
requires-python = ">=3.13"
version = "0.0.1"

dependencies = [
    "geopy>=2.4.1",
    "pycountry-convert>=0.7.2",
    "pydantic>=2.10.6",
    "pytest>=8.4.2",
]
[dependency-groups]
dev = [
    "notebook>=7.3.2",
]

[project.scripts]
cli = 'speciai.cli:main'

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
exclude = [
    ".direnv",
    ".devenv",
    ".output",
]

[tool.ruff]
extend-include = ["*.ipynb"]
target-version = "py313"
line-length = 88

[tool.ruff.lint]
extend-select = [
    "W605",   # pycodestyle: invalid-escape-sequence
    "S102",   # flake8-bandit: exec-builtin
    "INP",    # flake8-no-pep420
    "PYI",    # flake8-pyi
    "PT",     # flake8-pytest-style
    "PGH",    # pygrep-hooks
    "PL",     # Pylint
    "NPY",    # NumPy-specific rules
    "RUF",    # Ruff-specific rules
]
ignore = [
    "NPY002", # numpy-legacy-random
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
"tests/**" = ["INP001"]
"[!t][!e][!s][!t][!s]*/**" = ["PT"]
