name: "Setup Nix Environment"
description: "Sets up Nix"

runs:
  using: "composite"
  steps:
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
            extra-substituters = https://nix-community.cachix.org https://devenv.cachix.org
            extra-trusted-public-keys = nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= devenv.cachix.org-1:w1cLUi8dv3hnoSPGAuibQv+f9TZLr6cv/Hm9XgU50cw=
    - name: bootstrap
      run: |
        nix profile install "./tools/nix#devShells.x86_64-linux.ci"
        ./tools/ci/setup-git.sh
      shell: bash
